-- ============================================================
-- Wortspiel - Juego de Memoria Alemán-Español
-- Database
-- ============================================================
SET NAMES 'utf8mb4';
SET CHARACTER SET utf8mb4;

CREATE DATABASE IF NOT EXISTS wortspiel_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE wortspiel_db;

DROP TABLE IF EXISTS verbos;
CREATE TABLE verbos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    aleman VARCHAR(100) NOT NULL,
    espanol VARCHAR(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO verbos (aleman, espanol) VALUES
('sein', 'ser, estar'),
('haben', 'tener'),
('werden', 'volverse, llegar a ser'),
('können', 'poder, ser capaz de'),
('müssen', 'deber, tener que'),
('sagen', 'decir'),
('machen', 'hacer'),
('geben', 'dar'),
('kommen', 'venir, llegar'),
('sollen', 'deber'),
('wollen', 'querer'),
('gehen', 'ir'),
('wissen', 'saber'),
('sehen', 'ver'),
('lassen', 'dejar, permitir'),
('stehen', 'estar de pie'),
('finden', 'encontrar'),
('bleiben', 'quedarse'),
('liegen', 'yacer, estar acostado'),
('heißen', 'llamarse'),
('denken', 'pensar'),
('nehmen', 'tomar'),
('tun', 'hacer'),
('dürfen', 'poder, tener permiso para'),
('glauben', 'creer'),
('halten', 'sostener, mantener'),
('nennen', 'nombrar'),
('mögen', 'gustar'),
('zeigen', 'mostrar'),
('führen', 'liderar, guiar'),
('sprechen', 'hablar'),
('bringen', 'traer'),
('leben', 'vivir'),
('fahren', 'conducir, viajar'),
('meinen', 'opinar, pensar'),
('fragen', 'preguntar'),
('kennen', 'conocer'),
('gelten', 'valer, ser válido'),
('stellen', 'colocar, poner'),
('spielen', 'jugar'),
('arbeiten', 'trabajar'),
('brauchen', 'necesitar'),
('folgen', 'seguir'),
('lernen', 'aprender'),
('verstehen', 'entender'),
('setzen', 'poner, sentar'),
('bekommen', 'recibir'),
('beginnen', 'empezar, comenzar'),
('erzählen', 'contar, relatar'),
('versuchen', 'intentar'),
('schreiben', 'escribir'),
('laufen', 'correr'),
('erklären', 'explicar'),
('gehören', 'pertenecer'),
('entstehen', 'surgir'),
('erhalten', 'recibir, obtener'),
('suchen', 'buscar'),
('legen', 'poner, colocar'),
('vorstellen', 'presentar, imaginar'),
('handeln', 'actuar, negociar'),
('erreichen', 'alcanzar'),
('tragen', 'llevar, portar'),
('schaffen', 'crear, lograr'),
('lesen', 'leer'),
('verlieren', 'perder'),
('darstellen', 'representar'),
('erkennen', 'reconocer'),
('entwickeln', 'desarrollar'),
('reden', 'hablar'),
('aussehen', 'parecer, tener aspecto de'),
('erscheinen', 'aparecer'),
('bilden', 'formar'),
('anfangen', 'comenzar'),
('erwarten', 'esperar algo'),
('wohnen', 'vivir, residir'),
('betreffen', 'concernir, afectar'),
('warten', 'esperar'),
('vergehen', 'pasar el tiempo'),
('helfen', 'ayudar'),
('gewinnen', 'ganar'),
('schließen', 'cerrar'),
('fühlen', 'sentir'),
('bieten', 'ofrecer'),
('interessieren', 'interesar'),
('erinnern', 'recordar'),
('ergeben', 'resultar en'),
('annehmen', 'aceptar'),
('studieren', 'estudiar'),
('verbinden', 'conectar, unir'),
('ansehen', 'mirar'),
('fehlen', 'faltar'),
('bedeuten', 'significar'),
('vergleichen', 'comparar'),
('lösen', 'resolver'),
('probieren', 'probar'),
('zuhören', 'escuchar'),
('anbieten', 'ofrecer'),
('fordern', 'exigir'),
('vorbereiten', 'preparar'),
('beantworten', 'responder'),
('verbessern', 'mejorar'),
('leiten', 'dirigir'),
('ändern', 'cambiar'),
('entdecken', 'descubrir'),
('hoffen', 'esperar con esperanza'),
('teilen', 'compartir'),
('reagieren', 'reaccionar'),
('schätzen', 'valorar'),
('anwenden', 'aplicar'),
('verwenden', 'usar'),
('prüfen', 'verificar'),
('bestimmen', 'determinar'),
('bestehen', 'existir'),
('beziehen', 'referirse'),
('überlegen', 'reflexionar'),
('erwähnen', 'mencionar'),
('empfinden', 'sentir'),
('entscheiden', 'decidir'),
('erfahren', 'experimentar'),
('bemerken', 'notar'),
('sorgen', 'preocuparse'),
('wachsen', 'crecer'),
('garantieren', 'garantizar'),
('betreuen', 'cuidar'),
('analysieren', 'analizar'),
('kritisieren', 'criticar'),
('versprechen', 'prometer'),
('erlauben', 'permitir'),
('beschreiben', 'describir'),
('begründen', 'justificar'),
('beeinflussen', 'influenciar'),
('bezeichnen', 'describir'),
('überwinden', 'superar'),
('stören', 'molestar'),
('verhindern', 'evitar'),
('unterstützen', 'apoyar'),
('erzeugen', 'producir'),
('überzeugen', 'convencer'),
('benutzen', 'usar'),
('aufhören', 'detener');
